=pod

=encoding utf8

=head1 NAME

grafana-dashboard-helper.namemaprule

=head1 DESCRIPTION

grafana-dashboard-helper.namerules specifies rules of translation from
InfluxDB measurement name and field name to
Grafana dashboard name and block name.

=over 8

IfluxDB                          Grafana
-----------------------------    ----------------------------
measurement name + field name => dashboard name + block name

=back

Block names are used internal processing and are hidden on Grafana dashboards.

If several pairs of measurement and field have same dashboard name and
block name, they will be merged and the dashboard name + block name will always
be unique within Grafana.

=head1 AUTHOR

SASAJIMA, Toshihiro

=head1 SEE ALSO

L<grafana-dashboard-helper.templaterule>

