=pod

=encoding utf8

=head1 NAME

grafana-dashboard-helper.conf

=head1 DESCRIPTION

grafana-dashboard-helper.conf is a configuration file
relateing the helper daemon.

=over 8

=item B<LISTENADDR>, B<LISTENPORT>

This specifies address / port which be listened by helper daemon.
 
=item B<HELPERURL>

This specifies URL of the helper which provided to browsers.
If the helper is provided via a reverse proxy, it specifies 
the proxy URL.

=item B<INFLUXURL>, B<INFLUXUSER>, B<INFLUXPASSWORD>, B<INFLUXDATABASE>

grafana-dashboard-helper fetches all measurements and fields from InfluxDB.

=item B<GRAFANAURL>, B<GRAFANAAPIKEY>, B<GRAFANAORGID>, B<GRAFANADATASOURCE>

grafana-dashboard-helper creates Grafana dashboads automatically.

=item B<MEASUREMENT_FILTER>

If you want to restrict dashboard creation with several measurements
in InfluxDB, you may specify MEASUREMENT_FILTER.
MEASUREMENT_FILTER is regular expression (Perl compatible), and
only measurements which name matchs MEASUREMENT_FILTER are created dashboards.

=item B<DEBUG>

You want to output more verbose logs, specify 1 .

=back

=head1 AUTHOR

SASAJIMA, Toshihiro

=head1 SEE ALSO

L<grafana-dashboard-helper(1)>

