grafana-dashboard-helper		usr/bin

get_series_from_influxdb		usr/lib/grafana-dashboard-helper
update_unused_series			usr/lib/grafana-dashboard-helper
validate_dashboard			usr/lib/grafana-dashboard-helper
prepare_dashboard			usr/lib/grafana-dashboard-helper
upload_dashboard_to_grafana		usr/lib/grafana-dashboard-helper
generate_index				usr/lib/grafana-dashboard-helper
cleanup_panelblocks_older_than_plugins	usr/lib/grafana-dashboard-helper

grafana-dashboard-helper.conf		etc/grafana-dashboard-helper
40_ncrt_agenterror.sh			etc/grafana-dashboard-helper/dashboard-plugins
40_ncrt_blockdevice.sh			etc/grafana-dashboard-helper/dashboard-plugins
40_ncrt_storage.sh			etc/grafana-dashboard-helper/dashboard-plugins
40_ncrt_nic.sh				etc/grafana-dashboard-helper/dashboard-plugins
50_ncrt_generic_volume.sh		etc/grafana-dashboard-helper/dashboard-plugins
60_ncrt_generic.sh			etc/grafana-dashboard-helper/dashboard-plugins
90_generic.sh				etc/grafana-dashboard-helper/dashboard-plugins
